add textfield ui component
Illusory-Team/work-fly-client pull request #10
Opened 2023-01-04 15:28 UTC by OddEer0

2023-01-04 18:39 UTC, edword03 requested changes

2023-01-04 18:39 UTC, edword03 commented on src/components/ui/inputs/TextField/TextField.tsx
> +					disabled={false}
А как инпут делать disabled, если он всегда false?

2023-01-04 18:39 UTC, edword03 commented on src/components/ui/inputs/TextField/TextField.tsx
> +	const firstType = useRef(type);
Реф дишний, если нигде не назначается

2023-01-04 18:39 UTC, edword03 commented on src/components/ui/inputs/TextField/TextField.tsx
> +		if (firstType.current === 'password') {
у тебя проверка уже есть в setInputType, тут она бесмыслена, тем более, что реф скорее всего nulll, т.к никуда не присваевается

2023-01-04 18:39 UTC, edword03 commented on src/components/ui/inputs/TextField/TextField.tsx
> +					placeholder={placeholder ? placeholder : firstType.current}
просто placeholder

2023-01-04 19:50 UTC, simple-russia commented on src/components/ui/inputs/TextField/TextField.module.scss
> +		/* stylelint-disable-next-line */
мб стоит пофиксить?

2023-01-04 19:50 UTC, simple-russia commented on src/components/ui/inputs/TextField/TextField.tsx
> +			setInputType((prev) => (prev === 'text' ? 'password' : 'text'));
не совсем понятная строка, думаю можно упростить

2023-01-04 19:50 UTC, simple-russia commented on src/components/ui/inputs/TextField/TextField.tsx
> +			)}
можно заменить &&

2023-01-04 19:50 UTC, simple-russia commented on src/components/ui/inputs/TextField/TextField.tsx
> +export default TextField;
почему дефолтный экспорт?

2023-01-05 07:22 UTC, OddEer0 commented on src/components/ui/inputs/TextField/TextField.module.scss
> +		/* stylelint-disable-next-line */
Я пробовал, получилось так что она стало хуже читаться. Там просит что бы селекторы инпутов были первее. а потом уже hover focus и тд. Таким образом потом с ней разбираться будет ещё труднее

2023-01-05 07:28 UTC, OddEer0 commented on src/components/ui/inputs/TextField/TextField.tsx
> +	const firstType = useRef(type);
Этот реф сохраняет первоначальный тип инпута, так как стейт с типом меняется не совсем возможно понять, какой тип у первоначального инпута.

2023-01-05 07:38 UTC, OddEer0 commented on src/components/ui/inputs/TextField/TextField.tsx
> +		if (firstType.current === 'password') {
ref сохраняет тип, так же как т стейт. Но в отличий от стейта она не меняет свой первоначальный тип. Это сделано специально для типа password. Обработчик данного типа, отрабатывает лишь в случай password что бы менять стейт на text или password. Хотя вместо рефа можно использовать props так что думаю да, реф стоит убрать

2023-01-05 07:39 UTC, OddEer0 commented on src/components/ui/inputs/TextField/TextField.tsx
> +					placeholder={placeholder ? placeholder : firstType.current}
Ну заумка, что если placeholder нет, то она будет тип инпута. В целом исправлю

2023-01-05 07:39 UTC, OddEer0 commented on src/components/ui/inputs/TextField/TextField.tsx
> +			setInputType((prev) => (prev === 'text' ? 'password' : 'text'));
Да, реф уберу. Вместо неё будет props type

2023-01-05 07:40 UTC, OddEer0 commented on src/components/ui/inputs/TextField/TextField.tsx
> +			)}
Не люблю я так)))) Но ладно

2023-01-05 07:40 UTC, OddEer0 commented on src/components/ui/inputs/TextField/TextField.tsx
> +export default TextField;
А почему нет?

2023-01-05 19:12 UTC, edword03 approved these changes

2023-01-05 19:12 UTC, merged