add checkbox component
Illusory-Team/work-fly-client pull request #11
Opened 2023-01-06 19:09 UTC by OddEer0

2023-01-06 21:55 UTC, edword03 requested changes
Отсутсвуют поведения при ховере и клике.

2023-01-06 21:55 UTC, edword03 commented on src/components/ui/inputs/Checkbox/Checkbox.module.scss
> +
Чекбокс так скрывать не надо, будет страдать accessibility, он у тебя должен оставаться на странице, вместо `display:none` лучше задай `opacity: 0; visibility: hidden`

2023-01-06 21:55 UTC, edword03 commented on src/components/ui/inputs/Checkbox/Checkbox.tsx
> +			</label>
В чем смысл этого выражения?

2023-01-06 21:55 UTC, edword03 commented on src/components/ui/inputs/Checkbox/Checkbox.module.scss
> +}
Для чего лейбл делать абсолютом и позиционировать относительно чекбокса? А если рядом или выше контент будет? он с ними слияется

2023-01-06 21:55 UTC, edword03 commented on src/components/ui/inputs/Checkbox/Checkbox.types.ts
> +type CheckboxSize = 'l' | 'm';
лучше не сокращать, тем более нижу у тебя полностью пропы написаны

2023-01-06 21:55 UTC, edword03 commented on src/components/ui/inputs/Checkbox/index.ts
> +export { default } from './Checkbox';
Мы договорились на именованный экспорт, а ты дефолтный ре-экспортируешь. Это нужно для удобства и сторибука, он работает только с именованными экспортами

2023-01-06 21:55 UTC, edword03 commented on src/components/ui/inputs/Checkbox/Checkbox.tsx
> +	const clNotChecked = classNames(styles.interface, styles.notChecked);
Если неудобно так называть, лучше экспортируй `cn`, вместо `classNames`

2023-01-07 11:33 UTC, OddEer0 commented on src/components/ui/inputs/Checkbox/Checkbox.module.scss
> +}
Ну так у инпута так же message через абсолют. Да и растояние сам можешь там поднастроить. А если надо подправить то нужно сделать ещё обертку и уже с эту обертку пихать

2023-01-07 11:35 UTC, OddEer0 commented on src/components/ui/inputs/Checkbox/index.ts
> +export { default } from './Checkbox';
понял

2023-01-07 11:35 UTC, OddEer0 commented on src/components/ui/inputs/Checkbox/Checkbox.tsx
> +	const clNotChecked = classNames(styles.interface, styles.notChecked);
Ну дискомфорта не вызывает

2023-01-07 11:37 UTC, OddEer0 commented on src/components/ui/inputs/Checkbox/Checkbox.tsx
> +			</label>
Ну вообще задумка, что по умолчанию ничего нет а только border должен быть. А если в пропсах передать то она появится как иконка. Но я сейчас не учел тут одно. Надо подправить

2023-01-07 11:38 UTC, OddEer0 commented on src/components/ui/inputs/Checkbox/Checkbox.module.scss
> +
Понял

2023-01-07 15:26 UTC, edword03 approved these changes

2023-01-07 16:01 UTC, simple-russia commented on src/components/ui/inputs/Checkbox/Checkbox.tsx
> +						<path d="M12 5C11.72 5 11.47 5.11 11.29 5.29L7 9.59L4.71 7.29C4.53 7.11 4.28 7 4 7C3.45 7 3 7.45 3 8C3 8.28 3.11 8.53 3.29 8.71L6.29 11.71C6.47 11.89 6.72 12 7 12C7.28 12 7.53 11.89 7.71 11.71L
наверное было бы неплохо вынести куда-то эту большущую SVG, хз :)

2023-01-07 16:06 UTC, simple-russia approved these changes

2023-01-07 16:06 UTC, merged