Feature/861m5a6p1 add auth-page
Illusory-Team/work-fly-client pull request #15
Opened 2023-01-12 14:32 UTC by OddEer0

2023-01-12 15:15 UTC, edword03 requested changes
1. Формы и слайдер это не **ui**
2. не совсем понимаю, что ты собираешься делать со страницей авторизации, когда у тебя там динамическая страница, не проще вынести в отдельный страницы `login` и `register`? 
3. Лого вынести в спрайты

2023-01-12 15:15 UTC, edword03 commented on src/components/screens/Auth/Auth.tsx
> +					</h1>
Вынести в компонент `Title`

2023-01-12 15:15 UTC, edword03 commented on src/styles/globals.scss
> +	min-width: 375px;
Лишнее, лучше в контейнер задавать

2023-01-12 15:15 UTC, edword03 commented on src/components/ui/inputs/TextField/TextField.tsx
> +			CustomIcon ? styles.isIcon : '',
просто `styles.icon`

2023-01-12 15:15 UTC, edword03 commented on src/components/ui/inputs/TextField/TextField.tsx
> +import { Icon } from '../../Icon';
Алиас

2023-01-12 15:15 UTC, edword03 commented on src/components/ui/forms/RegistrationForm/RegistrationForm.tsx
> +			<p className={styles.subTitle}>Please, enter your e-mail or phone number to login</p>
Текст лучше пропсами проикдывать

2023-01-12 15:15 UTC, edword03 commented on src/components/ui/carousel/MobileAuthCarousel/MobileAuthCarousel.tsx
> +				<Image className="m-0-a" src="/auth-illustration-1.png" width={278} height={278} alt="" priority />
alt заполнить

2023-01-12 15:15 UTC, edword03 commented on src/components/layouts/AuthLayout/Header/Header.tsx
> +	const isLogin = query.auth_type === 'login';
Как ты собираешься переходить на страницу с динамическим роутом, при том, что это страница авторизации?

И у тебя эта логика в 2х местах повторяется

2023-01-12 15:15 UTC, edword03 commented on src/components/screens/Auth/Auth.tsx
> +	const isLogin = query.auth_type === 'login';
Тоже самое

2023-01-12 15:15 UTC, edword03 commented on src/components/ui/inputs/Checkbox/Checkbox.tsx
> +					{checkedIcon ? checkedIcon : <Icon name="other_yes" className={styles.defaultIcon} />}
Не проще просто делать проверку на icon url, чем прокидываьть Иконку как компонент? 

`<Icon name={icon  ? icon  : 'other_yes'} className={styles.defaultIcon} />`

2023-01-12 15:15 UTC, edword03 commented on src/components/ui/inputs/TextField/TextField.tsx
> +							)}
тоже самое
`<Icon name={icon ? inputType === 'text' ? "other_show" : "other_closed" : icon} width={24} height={24} />`

2023-01-12 17:42 UTC, OddEer0 commented on src/components/ui/inputs/TextField/TextField.tsx
> +							)}
Ну да, там просто до этого были ноды и я тупо их так поменял, хотя надо было так делать

2023-01-12 17:45 UTC, OddEer0 commented on src/styles/globals.scss
> +	min-width: 375px;
Понял

2023-01-12 17:48 UTC, OddEer0 commented on src/components/layouts/AuthLayout/Header/Header.tsx
> +	const isLogin = query.auth_type === 'login';
Ну, по сути страница регистраций и логина одинаковая, подумал про вариант условного рендеринга в зависимости от query как бы так, условный рендеринг требуется в 2х местах, в header и в Auth

2023-01-13 12:40 UTC, simple-russia requested changes
Все ок

2023-01-13 12:40 UTC, simple-russia commented on src/components/screens/Auth/AuthMobile/AuthMobile.tsx
> +				You have a code?{' '}
це шо

2023-01-13 12:40 UTC, simple-russia commented on src/components/ui/carousel/MobileAuthCarousel/MobileAuthCarousel.tsx
> +	// const settings = {
забыл убрать комментарии?

2023-01-13 12:40 UTC, simple-russia commented on src/components/ui/carousel/MobileAuthCarousel/MobileAuthCarousel.tsx
> +		// </Slider>
тут тоже

2023-01-13 12:40 UTC, simple-russia commented on src/components/ui/forms/LoginForm/LoginForm.tsx
> +		return data;
гига мега отсупы в этом файле? а что по линту?

2023-01-13 12:40 UTC, simple-russia commented on src/components/ui/forms/LoginForm/LoginForm.types.ts
> +	className?: string;
тоже 8 пробелов отступов?

2023-01-13 12:40 UTC, simple-russia commented on src/components/ui/forms/RegistrationForm/RegistrationForm.module.scss
> +	max-width: 647px;
и тут

2023-01-13 12:51 UTC, OddEer0 commented on src/components/screens/Auth/AuthMobile/AuthMobile.tsx
> +				You have a code?{' '}
> це шо

Так prettier так влепил слушаться не хочет

2023-01-13 12:52 UTC, OddEer0 commented on src/components/ui/carousel/MobileAuthCarousel/MobileAuthCarousel.tsx
> +	// const settings = {
Так я добавил карусель, Дима сказал не добавляй, я удалил но опций оставил пока что, мб все же карусель будет

2023-01-13 12:53 UTC, OddEer0 commented on src/components/ui/forms/RegistrationForm/RegistrationForm.module.scss
> +	max-width: 647px;
У меня все в порядке хз, может у жуков такое зрение

2023-01-13 13:35 UTC, OddEer0 commented on src/components/ui/carousel/MobileAuthCarousel/MobileAuthCarousel.tsx
> +				<Image className="m-0-a" src="/auth-illustration-1.png" width={278} height={278} alt="" priority />
Так он же стоит...

2023-01-13 13:37 UTC, OddEer0 commented on src/components/ui/inputs/Checkbox/Checkbox.tsx
> +					{checkedIcon ? checkedIcon : <Icon name="other_yes" className={styles.defaultIcon} />}
Ну, думаю что прокидывать компонент будет более гибкий способ, обычно такое много где практикуется

2023-01-13 15:27 UTC, Stepasha419a approved these changes

2023-01-13 15:30 UTC, Stepasha419a approved these changes

2023-01-13 21:09 UTC, edword03 approved these changes

2023-01-13 21:10 UTC, merged