[Refactor/864du4xyv]: new architecture
Illusory-Team/work-fly-client pull request #28
Opened 2023-01-30 13:46 UTC by OddEer0

2023-01-30 18:16 UTC, Stepasha419a approved these changes

2023-01-30 18:16 UTC, Stepasha419a commented on README.md
> +  ├── layouts ─
а где?

2023-01-30 18:16 UTC, Stepasha419a commented on src/entities/User/components/UserDrawer/index.tsx
> +	if (error) return <div>error</div>;
я надеюсь, что это пока на первое время)

2023-01-30 18:16 UTC, Stepasha419a commented on src/entities/User/components/UserDrawer/index.tsx
> +	if (error) return <div>error</div>;
а еще inline if, такое осуждаем

2023-01-30 18:16 UTC, Stepasha419a commented on src/entities/User/components/UserDrawer/index.tsx
> +					))}
вынеси таб в компоненту

2023-01-30 18:16 UTC, Stepasha419a commented on src/entities/User/components/UserDrawer/index.tsx
> +					))}
по хорошему еще вынести эти first/second/third в компоненты, так будет намного понятнее, что здесь происходит

2023-01-30 18:16 UTC, Stepasha419a commented on src/entities/User/components/UserDrawer/index.tsx
> +}
вынеси в типы, ибо компонент очень громоздкий только из-за верстки

2023-01-30 18:16 UTC, Stepasha419a commented on src/entities/User/components/ViewPersonalDetail/index.tsx
> +	if (isLoading) return <div>Loading</div>;
тоже инлайновые, но пока что перестану комментить к ним, надеюсь ты понял

2023-01-30 18:16 UTC, Stepasha419a commented on src/entities/User/components/ViewPersonalDetail/index.tsx
> +				</div>
вынеси это в компонент

2023-01-30 18:16 UTC, Stepasha419a commented on src/entities/User/types/IUser.ts
> +	id: Nullable<number | string>;
там точно string, уже наверняка, думаю)

2023-01-30 18:16 UTC, Stepasha419a commented on src/features/Auth/components/LoginForm/index.tsx
> +				</>
вынеси в отдельный компонент

2023-01-30 18:16 UTC, Stepasha419a commented on src/features/Auth/components/LoginForm/index.tsx
> +			</form>
тоже вынести можно

2023-01-30 18:16 UTC, Stepasha419a commented on src/entities/User/model/user.slice.ts
> +	id: '',
назови это свойство по-другому, это путает

2023-01-30 18:16 UTC, Stepasha419a commented on src/pages/auth/registration.tsx
> +				form={<LoginForm className="mt-20" />}
здесь разве не RegistrationForm? В features у тебя даже её упоминания нету, ты отрисовываешь 2 LoginForm

2023-01-30 18:16 UTC, Stepasha419a commented on src/shared/ui/Meta/index.tsx
> +};
зачем ты продублировал один и тот же компонент в Meta.tsx и index.tsx файлах?

2023-01-30 18:23 UTC, edword03 approved these changes

2023-01-30 18:23 UTC, edword03 commented on README.md
> +  ├── layouts ─
забыл убрать

2023-01-30 18:23 UTC, edword03 commented on src/entities/User/components/UserDrawer/index.tsx
> +import { IUser, IUserTabs } from '../../types';
алиас

2023-01-30 18:23 UTC, edword03 commented on src/entities/User/components/ViewPersonalDetail/index.tsx
> +				</div>
можно вынести в компонент

2023-01-30 18:23 UTC, edword03 commented on src/features/Auth/components/LoginForm/index.tsx
> +	const { submitHandler, getEmailInputProps, getPasswordInputProps } = useLoginHookForm();
без hook

2023-01-30 18:23 UTC, edword03 commented on src/features/Auth/components/LoginForm/index.tsx
> +import { FormTemplate } from '@/entities/User';
а какое отношение эта форма имеет к пользователю?

2023-01-30 18:23 UTC, edword03 commented on src/features/Auth/components/LoginForm/index.tsx
> +			}
это логичнее бы относилось к children

2023-01-30 18:23 UTC, edword03 commented on src/features/Auth/types/Auth.ts
> +}
а это все логичнее бы отнести к entitie, по сути весь auth это как сущность может быть

2023-01-30 18:23 UTC, edword03 commented on src/pages/auth/registration.tsx
> +				form={<LoginForm className="mt-20" />}
children?

2023-01-30 18:23 UTC, edword03 commented on src/shared/api/axios.ts
> +const FAKE_URL = 'https://6358ff89ff3d7bddb99618ca.mockapi.io/';
вынести в env файл

2023-01-30 18:23 UTC, edword03 commented on src/shared/hooks/useAppSelector.ts
> +import { AppState } from '@/app/store/store';
у тебя папка application называется, как еще ошибка не вылезла?

2023-01-30 18:23 UTC, edword03 commented on src/shared/ui/Meta/Meta.tsx
> +			)}
страно только по description делать не публичной страницу

2023-01-30 18:23 UTC, edword03 commented on src/shared/ui/Meta/index.tsx
> +	);
почему код повторяется как в Meta/Meta.tsx?

2023-01-30 18:23 UTC, edword03 commented on src/widgets/AuthLayout/index.tsx
> +export const AuthLayout: FC<AuthProps> = ({
где то ты в index файлах делаешь ре-экспорт, а где то пишешь как компонент, хоть однообразие соблюдай

2023-01-30 18:23 UTC, edword03 commented on src/widgets/UserProfile/index.tsx
> +	});
это бы вынести в кастомный хук в той же директории

2023-01-30 18:30 UTC, edword03 requested changes
Поправь замечания

2023-01-30 18:38 UTC, Stepasha419a requested changes
забыл статус изменить

2023-01-30 22:58 UTC, OddEer0 commented on src/entities/User/components/UserDrawer/index.tsx
> +import { IUser, IUserTabs } from '../../types';
Какой алиас? Это уже модуль само по себе. Теперь через алиасы можно получать данные которые задуманы отдавать через public api. А те что нельзя отдавать образом относительного импорта и будут получаться, кароче теперь импорты данных одного слайса так и импортируем.

2023-01-30 23:00 UTC, OddEer0 commented on src/features/Auth/components/LoginForm/index.tsx
> +import { FormTemplate } from '@/entities/User';
Это форма скелет над ней авторизационной формой. А вот сама форма находится в feature

2023-01-30 23:02 UTC, OddEer0 commented on src/features/Auth/types/Auth.ts
> +}
Если судить, auth не сущность по заявлению самих авторов fsd, auth это обертка над многочисленными feature user'а.

2023-01-30 23:03 UTC, OddEer0 commented on src/shared/api/axios.ts
> +const FAKE_URL = 'https://6358ff89ff3d7bddb99618ca.mockapi.io/';
Не умею, сам сделаешь))))

2023-01-30 23:04 UTC, OddEer0 commented on README.md
> +  ├── layouts ─
Ну это и потом можно

2023-01-30 23:04 UTC, OddEer0 commented on src/entities/User/components/ViewPersonalDetail/index.tsx
> +				</div>
Ну даже хз как назвать)

2023-01-30 23:04 UTC, OddEer0 commented on src/features/Auth/components/LoginForm/index.tsx
> +	const { submitHandler, getEmailInputProps, getPasswordInputProps } = useLoginHookForm();
Ну можно да

2023-01-30 23:05 UTC, OddEer0 commented on src/features/Auth/components/LoginForm/index.tsx
> +			}
Да пускай так будет, тут children выдавать как то тоже стрёмно

2023-01-30 23:06 UTC, OddEer0 commented on src/pages/auth/registration.tsx
> +				form={<LoginForm className="mt-20" />}
На самом деле тут логика в том что children может оказаться не форма а другие места так же, то есть children не явная, а вот пропс явно указывает куда она пойдёт

2023-01-30 23:07 UTC, OddEer0 commented on src/shared/hooks/useAppSelector.ts
> +import { AppState } from '@/app/store/store';
Так я назвал в tsconfig алиас @app а ссылка является application

2023-01-30 23:08 UTC, OddEer0 commented on src/shared/ui/Meta/Meta.tsx
> +			)}
Не особо шарю за мета теги. Ну можешь сам поправить. Я по факту скопипастил где то

2023-01-30 23:09 UTC, OddEer0 commented on src/entities/User/components/UserDrawer/index.tsx
> +	if (error) return <div>error</div>;
Да, на первое время, inline if норм. Что тебе не нравится

2023-01-30 23:10 UTC, OddEer0 commented on src/entities/User/components/UserDrawer/index.tsx
> +					))}
Слишком много декомпозиций. Излишняя декомпозиция не думаю что хорошо

2023-01-30 23:11 UTC, OddEer0 commented on src/entities/User/types/IUser.ts
> +	id: Nullable<number | string>;
Ну изначально при логине или регистраций у юзера ничего нет, я это учёл поэтому и поставил так

2023-01-30 23:13 UTC, OddEer0 commented on src/pages/auth/registration.tsx
> +				form={<LoginForm className="mt-20" />}
Это временно, само реализация регистраций нет, поставил логин форму что бы пока ошибок не ставила

2023-01-30 23:14 UTC, OddEer0 commented on src/shared/ui/Meta/index.tsx
> +};
Забыл удалить

2023-01-31 06:48 UTC, Stepasha419a commented on src/entities/User/components/UserDrawer/index.tsx
> +	if (error) return <div>error</div>;
Мизу говорит, что это плохо

2023-01-31 06:48 UTC, Stepasha419a commented on src/entities/User/types/IUser.ts
> +	id: Nullable<number | string>;
Я ничего не говорил про Nullable

2023-01-31 09:43 UTC, OddEer0 commented on src/entities/User/components/UserDrawer/index.tsx
> +	if (error) return <div>error</div>;
Ну он сказал, а он кто? Мне кажется это просто дело читабельности. Но этот синтаксис читабельный, ибо был придуман специально для небольшого кода. Этот код не читабелен если он был бы большим но увы. Да и это уже какая-то шиза

2023-01-31 09:45 UTC, OddEer0 commented on src/features/Auth/components/LoginForm/index.tsx
> +				</>
Нет, это тупо футер формы. и она состоит из 2 ссылок. Делать из этого компонент это вообще бред

2023-01-31 09:46 UTC, OddEer0 commented on src/features/Auth/components/LoginForm/index.tsx
> +				</>
так же в зависимости от страницы ссылки могут меняться да и их может и не быть вовсе

2023-01-31 10:21 UTC, OddEer0 commented on src/widgets/UserProfile/index.tsx
> +	});
Ну когда будешь делать Dashboard layout. ты это привяжешь к этому layout. А потом сам разберешься куда константы пихать а куда хуки. Это просто сделано с упором того что в будущем будем юзать её в этом layout и привяжем к ней

2023-01-31 12:09 UTC, edword03 commented on src/shared/hooks/useAppSelector.ts
> +import { AppState } from '@/app/store/store';
Это будет путать

2023-01-31 13:06 UTC, Stepasha419a approved these changes

2023-01-31 13:06 UTC, Stepasha419a commented on src/entities/User/model/user.slice.ts
> +	readonlyId: '',
сделай название поадекватнее, чтобы можно было понять, что это за свойство и за что оно отвечает

2023-01-31 16:25 UTC, Stepasha419a approved these changes

2023-01-31 21:21 UTC, edword03 approved these changes

2023-01-31 21:21 UTC, merged