[Refactor/861m7v1hf]: fix UserHead location structure
Illusory-Team/work-fly-client pull request #31
Opened 2023-02-12 10:57 UTC by OddEer0

2023-02-12 11:22 UTC, edword03 requested changes

2023-02-12 11:22 UTC, edword03 commented on .prettierrc
> +		"^@/app/(.*)$",
почему app?

2023-02-12 11:22 UTC, edword03 commented on pages/index.tsx
> +				<CompanyDrawer companyHead={<EntityHead isChangeable={true} title="dsadsa" subTitle="dsadsad" />} />
Ты под каждую сущность будешь drawer создавать?

2023-02-12 11:22 UTC, edword03 commented on src/entities/Company/components/CompanyDrawer/index.tsx
> +}
а чем бы просто children не передать с таким же успехом?

2023-02-12 11:22 UTC, edword03 commented on src/entities/User/components/UserDrawer/index.tsx
> +	userHead?: ReactNode;
код повторяется

2023-02-12 11:22 UTC, edword03 commented on src/features/UserActions/components/ChangeAvatar/index.tsx
> +};
в чем смысл компонента, если просто EntityHead возвращает?

2023-02-12 11:22 UTC, edword03 commented on src/shared/ui/EntityHead/EntityHead.types.ts
> +export interface EntityHeadProps extends InputHTMLAttributes<HTMLInputElement> {
зачем тут атрибуты инпута нужны? это не компонент импута в логичной его форме

2023-02-12 11:22 UTC, edword03 commented on src/widgets/DashboardLayout/components/UserProfile/index.tsx
>  		/>
тут тоже самое, возвращает 2 аналогичных компонента

2023-02-12 11:31 UTC, OddEer0 commented on .prettierrc
> +		"^@/app/(.*)$",
Потому что в tscondig назван как app но ссылается в application. Она не может быть application ибо алиас сделан в @/app виде.

2023-02-12 11:33 UTC, OddEer0 commented on pages/index.tsx
> +				<CompanyDrawer companyHead={<EntityHead isChangeable={true} title="dsadsa" subTitle="dsadsad" />} />
У них разные слоты могут быть, так же при изменений тела у одного в будущем могут возникнуть проблемы в другом, Хотя на данный момент верстка идентична и можно как-то назвать и поставить в shared.

2023-02-12 11:34 UTC, OddEer0 commented on src/entities/Company/components/CompanyDrawer/index.tsx
> +}
Это пока что, children можно будет передавать body которая по факту имеет логику

2023-02-12 11:35 UTC, OddEer0 commented on src/entities/User/components/UserDrawer/index.tsx
> +	userHead?: ReactNode;
Да, потому что разные Drawer хотя и схожие по сути кроме статусов и некоторых возможностей.

2023-02-12 11:36 UTC, OddEer0 commented on src/features/UserActions/components/ChangeAvatar/index.tsx
> +};
Заготовка на будущее, ибо этот компонент обёртка над EntityHead который будет выполнять изменение аватарки. Сама реализация должна быть отдельной таской

2023-02-12 11:37 UTC, OddEer0 commented on src/shared/ui/EntityHead/EntityHead.types.ts
> +export interface EntityHeadProps extends InputHTMLAttributes<HTMLInputElement> {
Она модернизировано в то, что теперь есть возможность загружать файлы через клик на аватарку, для обработки input типа file нужны будут именно эти пропсы

2023-02-12 11:39 UTC, OddEer0 commented on src/widgets/DashboardLayout/components/UserProfile/index.tsx
>  		/>
Вообще-то нет. На данный момент так и есть. Но после того как ChangeAvatar обработается до того, как будет менять  аватарку. Вот тогда уже не одно и тоже. По виду одно и тоже, но ChangeAvatar является уже фичей которая меняет аватарку

2023-02-12 13:33 UTC, Stepasha419a approved these changes

2023-02-12 13:33 UTC, Stepasha419a commented on src/shared/ui/EntityHead/EntityHead.tsx
> +						<input className={styles.input} ref={inputRef} type="file" {...props} />
если загружаются только картинки, то лучше сделать ограничение в виде атрибута
accept="image/png, image/jpeg"

2023-02-12 17:43 UTC, edword03 commented on src/shared/ui/EntityHead/EntityHead.types.ts
> +export interface EntityHeadProps extends InputHTMLAttributes<HTMLInputElement> {
Так явно указать эти типы и все

2023-02-13 14:45 UTC, Stepasha419a commented on src/shared/ui/EntityHead/EntityHead.tsx
> +							accept="image/png, image/jpeg"
я формально тогда сказал про "image/(something)", на самом деле можно просто прописать "image/*", чтобы принимались все расширения изображений

2023-02-13 14:45 UTC, Stepasha419a commented on src/shared/ui/EntityHead/EntityHead.types.ts
> +	value?: any;
в чем проблема?

2023-02-13 17:58 UTC, edword03 approved these changes

2023-02-13 18:00 UTC, merged