Feature/864dyug29: add FolderCard
Illusory-Team/work-fly-client pull request #33
Opened 2023-02-16 16:39 UTC by OddEer0

2023-02-17 09:01 UTC, Stepasha419a approved these changes

2023-02-17 09:01 UTC, Stepasha419a commented on src/entities/Folder/folder.service.ts
> +	},
зачем это?

2023-02-17 09:01 UTC, Stepasha419a commented on src/shared/ui/AvatarGroup/AvatarGroup.tsx
> +	const cl = classNames(styles.container, styles[size], className);
реализуй подмену отсутствующих аватаров инициалами сотрудника

2023-02-17 16:17 UTC, OddEer0 commented on src/entities/Folder/folder.service.ts
> +	},
Ну для запроса на фолдеры, ну пока как основу реализовал

2023-02-20 10:49 UTC, Stepasha419a approved these changes

2023-02-20 10:49 UTC, Stepasha419a commented on src/shared/ui/Avatar/Avatar.tsx
> +		<div style={{ background: defaultAvatar ? color : undefined }} className={cl} {...props}>
вынеси сразу с условием в переменную

2023-02-20 10:49 UTC, Stepasha419a commented on src/shared/ui/EntityHead/EntityHead.tsx
> +								alt=""
у тебя же prop alt и так по умолчанию = ""

2023-02-20 13:22 UTC, edword03 requested changes

2023-02-20 13:22 UTC, edword03 commented on pages/index.tsx
> +	const { data, isLoading } = useQuery('folder', () => FolderService.getOne('1'));
можно вынести

2023-02-20 13:22 UTC, edword03 commented on src/application/styles/helpers/_variables.scss
>  }
бред так делать

2023-02-20 13:22 UTC, edword03 commented on src/entities/Folder/components/FolderCard/index.tsx
> +	const AvatarGroupMembers = useMemo(() => {
с маленькой назови, чтобы не путать с компонентами

2023-02-20 13:22 UTC, edword03 commented on src/entities/Folder/components/FolderCard/index.tsx
> +	}, [data]);
да и так ли нужно тут `useMemo`?

2023-02-20 13:22 UTC, edword03 commented on src/entities/Folder/components/FolderCard/index.tsx
> +						<span>{data.tasks} tasks</span>
советую такие вставки оборачивать во какой то тег, чтобы не путаться

2023-02-20 13:22 UTC, edword03 commented on src/shared/helpers/getFirstLetters.ts
> +export const getFirstLetters = (string: string) => {
```diff
-string
+sentence 
```

2023-02-20 13:22 UTC, edword03 commented on src/shared/helpers/getFirstLetters.ts
> +	if (!str.length) return 'N';
если нету длины, лучше выбрасывать ошибку

2023-02-20 13:22 UTC, edword03 commented on src/shared/helpers/getFirstLetters.ts
> +	if (arr.length === 1) return str[0];
Лишнее, такого кейса не будет

2023-02-20 13:22 UTC, edword03 commented on src/shared/helpers/getFirstLetters.ts
> +		return result;
`return arr.reduce((acc, char) => acc = acc + char[0], '')`

2023-02-20 13:22 UTC, edword03 commented on src/shared/helpers/getFirstLetters.ts
> +	else {
условия убрать вообще

2023-02-20 13:22 UTC, edword03 commented on src/shared/helpers/getFirstLetters.ts
> +	const str = string.trim();
`const arrayStrings = string.trim().split(' ')`

2023-02-20 13:22 UTC, edword03 commented on src/shared/ui/Avatar/Avatar.tsx
> +	const color = defaultAvatar ? `var(--avatar-${(defaultAvatar.codePointAt(0) as number) % 10})` : '';
тоже странное решение

2023-02-20 13:22 UTC, edword03 commented on src/shared/ui/Avatar/Avatar.tsx
> +				children
children убрать, он тут не нужен будет

2023-02-20 13:22 UTC, edword03 commented on src/shared/ui/EntityHead/EntityHead.tsx
> +								alt=""
alt prop чем то заполняй, пустой строкой быть не должен

2023-02-20 13:59 UTC, Stepasha419a commented on src/shared/helpers/getFirstLetters.ts
> +	if (!str.length) return 'N';
а как её вообще не может быть, если уже с момента регистрации мы задаем fullname

2023-02-20 14:23 UTC, OddEer0 commented on src/shared/ui/AvatarGroup/AvatarGroup.tsx
> +	const cl = classNames(styles.container, styles[size], className);
Так уже сделано

2023-02-20 14:24 UTC, OddEer0 commented on src/shared/ui/Avatar/Avatar.tsx
> +		<div style={{ background: defaultAvatar ? color : undefined }} className={cl} {...props}>
Да, согласен, хорошее решение

2023-02-20 14:24 UTC, OddEer0 commented on pages/index.tsx
> +	const { data, isLoading } = useQuery('folder', () => FolderService.getOne('1'));
Так это index файл, где я тупо для тестов впихиваю, это не принципиально тут

2023-02-20 14:24 UTC, OddEer0 commented on src/application/styles/helpers/_variables.scss
>  }
А варианты??

2023-02-20 14:25 UTC, OddEer0 commented on src/entities/Folder/components/FolderCard/index.tsx
> +	const AvatarGroupMembers = useMemo(() => {
Да, по-моему я там забыл уже, на последнем издыханий правил)

2023-02-20 14:26 UTC, OddEer0 commented on src/entities/Folder/components/FolderCard/index.tsx
> +	}, [data]);
Ну, учитывая, что ты сказал в будущем там будет функционал с показом попапа с юзерами то да, имеет смысл

2023-02-20 14:27 UTC, OddEer0 commented on src/entities/Folder/components/FolderCard/index.tsx
> +						<span>{data.tasks} tasks</span>
А именно в какие

2023-02-20 14:28 UTC, OddEer0 commented on src/shared/ui/Avatar/Avatar.tsx
> +	const color = defaultAvatar ? `var(--avatar-${(defaultAvatar.codePointAt(0) as number) % 10})` : '';
Ну в переменную вынесу.

2023-02-20 14:29 UTC, OddEer0 commented on src/shared/ui/Avatar/Avatar.tsx
> +				children
Ну, тогда нельзя будет его называть так как хочешь через children ну и там делать иконочные аватарки условно

2023-02-20 14:29 UTC, OddEer0 commented on src/shared/ui/EntityHead/EntityHead.tsx
> +								alt=""
Понял

2023-02-20 15:31 UTC, edword03 commented on src/entities/Folder/components/FolderCard/index.tsx
> +						<span>{data.tasks} tasks</span>
да в тот же span например

2023-02-23 12:24 UTC, edword03 approved these changes

2023-02-23 12:24 UTC, merged