[migration/WF-149]: migrate custom ui to material ui
Illusory-Team/work-fly-client pull request #44
Opened 2023-06-14 05:17 UTC by OddEer0

## Task name

### Describe task

### Issue ticket number and link

### Screens/videos (if there)

### TBD (if there)

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] My code follows the style guidelines of this project
- [ ] If it is a core feature, I have added thorough tests.

2023-06-15 19:46 UTC, edword03 requested changes
1. Удали нафиг самописный cn
2. Зачем использовать Controller форм, когда можно обойтись прокидыванием пропсов?
3. Зачем добавил самописные утилиты, которые мы не обсуждали, это должны быть отдельные задачи вообще
4. Исправь ошибку chromium, там есть лог ошибки
5. В след раз не выходи за рамки своей задачи

2023-06-15 19:46 UTC, edword03 commented on src/application/providers/theme.provider.tsx
> +export const WithThemeProvider: FC<PropsWithChildren> = ({ children }) => {
Это не hoc

2023-06-15 19:46 UTC, edword03 commented on src/entities/Notification/components/NotificationList/index.tsx
> +						<NotificationCard className={styles.notificationCard} key={notification.id} data={notification} />
Нафига так делать?

2023-06-15 19:46 UTC, edword03 commented on src/entities/Notification/components/NotificationCard/index.tsx
> +	const { date, folder_name, priority, src, subTitle, title } = data;
чем тебе деструктуризация пропсов в функции не устроила

2023-06-15 19:46 UTC, edword03 commented on src/entities/User/components/ProfileTemplate/index.tsx
> +							src={data.avatar || undefined}
зачем undefined передавать?

2023-06-15 19:46 UTC, edword03 commented on src/shared/package/react-hooks/core/useCopyToClickboard.ts
> +type CopyFn = (text: string) => Promise<boolean>
Сделай нормальный нейминг

2023-06-15 19:46 UTC, edword03 commented on src/shared/package/react-hooks/utility/useIsomorphicLayoutEffect.ts
> +export const useIsomorphicLayoutEffect = typeof window !== "undefined" ? useLayoutEffect : useEffect
В чем смысл этого хука, если в обоих случая не будет работать, если window === undefined?))

2023-06-17 09:13 UTC, dmitryduy commented on src/application/theme/typography.ts
> +	}
почему бы не сделать `Record<'headline' | 'subhead'..., React.CSSProperties>`

2023-06-17 09:13 UTC, dmitryduy commented on src/entities/Company/components/CompanyDrawer/index.tsx
> +		<Drawer anchor="right" onClose={closeHandler} open={true}>
соблюдается ли наименование? везде в коде хендлены начинаются на on?

2023-06-17 09:13 UTC, dmitryduy commented on src/entities/Folder/components/FolderCard/FolderCard.module.scss
> +	width: calc(100% - 36px - 11px);
почему отнимаешь 36 и 11 пикселей? мб это вынести в константы, чтобы понимать, что это такое

2023-06-17 09:13 UTC, dmitryduy commented on src/entities/Folder/components/FolderCard/index.tsx
> +							<Avatar size="small" src={AVATAR2_URL} />
почему не сделать через `map`?

2023-06-17 09:13 UTC, dmitryduy commented on src/entities/Notification/components/AddNotificationDrawer/index.tsx
> +	// FIX ME - а точно ли будем стейт менеджер для этого юзать?
Лучше вопросы писать не в коде, а в какой нибудь джире

2023-06-17 09:13 UTC, dmitryduy commented on src/entities/User/components/ProfileTemplate/index.tsx
> +							alt={data ? `${data.firstName} ${data.lastName}` : ''}
почему ты ушел от опционального оператора?

2023-06-17 09:13 UTC, dmitryduy commented on src/entities/User/components/ProfileTemplate/index.tsx
> +						<TabPanel key={i} value={selectTab} index={i + 1}>
у тебя табы не будут удаляться или меняться метами? Если будут, то ключ лучше другой подобрать

2023-06-17 09:13 UTC, dmitryduy commented on src/features/UserActions/components/ChangePersonalDetail/index.tsx
> +				<FormControl className={styles.control}>
`FormControl` можно вынести в отдельный компонент, чтобы не было такого дублирования кода

2023-06-17 09:13 UTC, dmitryduy commented on src/features/UserActions/lib/hooks/useChangePersonalDetail.ts
> +		console.log(data);
зачем тут вывод в консоль?

2023-06-17 09:13 UTC, dmitryduy commented on src/features/UserActions/lib/hooks/usePasswordChange.ts
> +		console.log(data);
Зачем тут вывод в консоль?

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/lib/hooks/useActions.ts
>  export const useActions = (action: any) => {
Вообще разрабы [не рекомендуют](https://github.com/reduxjs/react-redux/issues/1252#issuecomment-488160930) юзать этот хук

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useCopyToClickboard.ts
> +	return [copiedText, copy]
почему нет точек с запятой?

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useDebounce.ts
> +	const timeout = useRef<any>(null)
вместо `any` пиши `Nodejs.Timer`

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useDebounce.ts
> +}
Тоже нет точек с запятой

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useElementSize.ts
> +	width: number
где точки с запятой? Настрой притиер и eslint и пройдись по всему коду

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useImageChange.ts
> +		}
можно `callback && callback()`

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useIntersectionObserver.ts
> +	return entry
То есть в IOS это не будет работать? может быть тогда сделать через `MutationObserver`? `MutationObserver` работает на IOS

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useLockedBody.ts
> +	return [locked, setLocked]
Нужны ли здесь все эти комментарии?

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useMediaQuery.ts
> +		handleChange()
Такое ощущение, что у тебя эта функция будет накапливаться, ты же ее не обернул в `useCallback`. Проверь этот момент

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useOutsideClick.ts
> +			document.removeEventListener("click", handleClickOutside, true)
Тоже самое, такое ощущение, что обработчики будут копиться, а не удаляться

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useThrottleCallback.ts
> +export const useThrottleCallback = (callback: () => void, CD: number) => {
Не ясно, что такое `CD`. Сделай более читаемое название переменной

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useToggle.ts
> +	const cd = useRef(true)
Название переменной не говорящее, переименуй

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useToggle.ts
> +			firstCallback()
можно написать `firstCallback && firstCallback()`

2023-06-17 09:13 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useToggle.ts
> +}
В челом очень замудреный хук. Не понятно, что он делает, попробуй как то упростить. Или напиши мне, объявни, что он должен делать

2023-06-17 09:13 UTC, dmitryduy commented on src/widgets/PageLayout/components/Header/index.tsx
> +								alt={user ? `${user.firstName} ${user.lastName}` : undefined}
У изображения всегда должен быть `alt` атрибут

2023-06-17 09:59 UTC, OddEer0 commented on src/application/providers/theme.provider.tsx
> +export const WithThemeProvider: FC<PropsWithChildren> = ({ children }) => {
это провайдер, обычно это не особо плохо. Тут возможно будет логика темизаций, поэтому обычно это выносят

2023-06-17 10:05 UTC, OddEer0 commented on src/entities/Notification/components/NotificationList/index.tsx
> +						<NotificationCard className={styles.notificationCard} key={notification.id} data={notification} />
Компонент привязан к модели notification. Поэтому думаю тут не имеет смысла описывать все значения, которые нужны компоненте. И более понятный вариант, чем spread оператор.

2023-06-17 10:06 UTC, OddEer0 commented on src/entities/Notification/components/NotificationList/index.tsx
> +						<NotificationCard className={styles.notificationCard} key={notification.id} data={notification} />
Но возможно это нарушает 4 SOLID принцип, но в таком случае что мой вариант, что вариант через spread оператор не будет подходить. В любом случае тогда нужно будет прокидывать пропсы по одному, либо сделать специальный геттер пропсов для этого

2023-06-17 10:08 UTC, OddEer0 commented on src/entities/Notification/components/NotificationCard/index.tsx
> +	const { date, folder_name, priority, src, subTitle, title } = data;
Можно и таким способом, но на самом деле вкусовщина как по мне

2023-06-17 10:08 UTC, OddEer0 commented on src/entities/User/components/ProfileTemplate/index.tsx
> +							src={data.avatar || undefined}
Вроде тут я работал с типами, изначально хотел передать null, но потом забыл поменять

2023-06-17 10:12 UTC, OddEer0 commented on src/shared/package/react-hooks/utility/useIsomorphicLayoutEffect.ts
> +export const useIsomorphicLayoutEffect = typeof window !== "undefined" ? useLayoutEffect : useEffect
Это утилитарный хук. Который работает и для SSR и для CSR. В случае если есть window, то отработает LayoutEffect. В обратном(То есть SSR отработает в  виде useEffect). Кратко говоря утилитарный хук что бы постоянно не делать защиту от SSR в других хуках

2023-06-17 10:14 UTC, OddEer0 commented on src/entities/Folder/components/FolderCard/index.tsx
> +							<Avatar size="small" src={AVATAR2_URL} />
Тут пока не понятно костыль, мы ещё не решили как это дело будет приходить с бэка. Сделано чисто ради визуала.

2023-06-17 10:15 UTC, OddEer0 commented on src/shared/package/react-hooks/core/useThrottleCallback.ts
> +export const useThrottleCallback = (callback: () => void, CD: number) => {
Ну на самом деле надо переименовать в Delay, данный хук сделан очень давно.

2023-06-17 10:16 UTC, OddEer0 commented on src/shared/package/react-hooks/core/useToggle.ts
> +}
Хук простой, и юзается как обычный toggle. Его смысл в том, что у него есть дополнительный функционал в виде троттлера и функциями, которые могут отрабатывать при переключений с true false

2023-06-17 10:18 UTC, OddEer0 commented on src/widgets/PageLayout/components/Header/index.tsx
> +								alt={user ? `${user.firstName} ${user.lastName}` : undefined}
Да, но мы пока ещё не поменяли стор, я думаю что effector будет принимать данные и маппить. Там будет свойство fullName. А сейчас это костыльно прикреплено

2023-06-17 10:25 UTC, edword03 commented on src/application/providers/theme.provider.tsx
> +export const WithThemeProvider: FC<PropsWithChildren> = ({ children }) => {
я про именование, это не хок, поэтому не надо писать с `with`

2023-06-17 10:30 UTC, OddEer0 commented on src/application/providers/theme.provider.tsx
> +export const WithThemeProvider: FC<PropsWithChildren> = ({ children }) => {
Ну, я видел в примерах такое написание поэтому так сделал.

2023-06-17 12:01 UTC, OddEer0 commented on src/application/theme/typography.ts
> +	}
Линтер ругается)

2023-06-17 12:05 UTC, Columbiya commented on src/entities/User/hooks/useProfile.ts
>  	};
а нужен ли disable вообще? лучше удалить айдишник, если он там не нужен, а не подавлять его

2023-06-17 12:11 UTC, OddEer0 commented on src/shared/package/react-hooks/core/useToggle.ts
> +}
А, планируется написания документаций для хуков в storybook

2023-06-17 12:12 UTC, OddEer0 commented on src/entities/User/hooks/useProfile.ts
>  	};
Это на основе redux, мы планируем перейти на effector, этот хук в любом случае поменяется

2023-06-17 12:30 UTC, OddEer0 commented on src/entities/User/components/ProfileTemplate/index.tsx
> +							alt={data ? `${data.firstName} ${data.lastName}` : ''}
беда с типизацией. с ней надо разбираться при миграций в другой стор.

2023-06-17 12:31 UTC, Columbiya commented on src/widgets/PageLayout/components/UserProfile/index.tsx
>  	const tabs: IUserTabs[] = [
если так делать, то лучше табы в useMemo оборачивать
сейчас они каждый раз будут новые создаваться и ререндериться при ререндере UserProfile

2023-06-17 12:32 UTC, OddEer0 commented on src/entities/User/components/ProfileTemplate/index.tsx
> +						<TabPanel key={i} value={selectTab} index={i + 1}>
будут удаляться, но внутри компонента TabPanel, тут это не играет роли.

2023-06-17 12:33 UTC, OddEer0 commented on src/features/UserActions/components/ChangePersonalDetail/index.tsx
> +				<FormControl className={styles.control}>
Ну Mui именно так использует в примерах. Есть впринципе вариант как в TextField поставить уже с FormControl

2023-06-17 12:36 UTC, OddEer0 commented on src/features/UserActions/lib/hooks/useChangePersonalDetail.ts
> +		console.log(data);
Хук сделан на будущее, самой логики нет. Поэтому стоит для того что бы смотреть вывод даты с формы

2023-06-17 12:37 UTC, OddEer0 commented on src/shared/lib/hooks/useActions.ts
>  export const useActions = (action: any) => {
Это задумка VES edvord. Она на самом деле и архитектуру не соблюдает. Да и впринципе у effector есть получше решение, на неё планируем перейти

2023-06-17 12:39 UTC, OddEer0 commented on src/shared/package/react-hooks/core/useCopyToClickboard.ts
> +	return [copiedText, copy]
С другого проекта привозил

2023-06-17 12:41 UTC, OddEer0 commented on src/shared/package/react-hooks/core/useDebounce.ts
> +	const timeout = useRef<any>(null)
всё равно ругается

2023-06-17 12:45 UTC, OddEer0 commented on src/shared/package/react-hooks/core/useMediaQuery.ts
> +		handleChange()
Можно удалить даже, mui предоставляет свой

2023-06-18 12:07 UTC, edword03 approved these changes

2023-06-20 11:50 UTC, Stepasha419a approved these changes

2023-06-20 11:50 UTC, Stepasha419a commented on .eslintrc.json
> -		"import/order": [
правила прям железно убрал? Если они мешают работе с mui

2023-06-20 11:50 UTC, Stepasha419a commented on src/entities/User/components/ProfileTemplate/index.tsx
> +							alt={data ? `${data.firstName} ${data.lastName}` : ''}
тут еще от реализации зависит, нужно сделать такие поля на бэке (сейчас только fullName). Сейчас больше свелось к тому, что lastName поля может и не быть, потому что оно опциональное (при регистрации заполняется только firstName). По хорошему - переделать регистрацию на большее количество полей

2023-06-20 11:50 UTC, Stepasha419a commented on src/entities/User/model/user.slice.ts
> +				lastName: '',
поля лучше сделать по дефолту null (в самой бд они будут иметь такое значение при создании)

2023-06-20 11:50 UTC, Stepasha419a commented on src/features/UserActions/components/ChangePersonalDetail/index.tsx
> +				<FormControl className={styles.control}>
тут вынесение ради вынесения будет, скорее всего, потому что слишком много чего может измениться спустя время (добавление новой формы и тд)

2023-06-20 11:50 UTC, Stepasha419a commented on src/shared/api/types/User.ts
> +	avatar: string;
также nullable поле, почему ты его убрал?

2023-06-20 11:50 UTC, Stepasha419a commented on src/shared/ui/inputs/TextArea/TextArea.tsx
>  export const TextArea: FC<PropsWithChildren<TextAreaProps>> = ({ label = '', className = '', children, ...props }) => {
то есть будет использоваться и старый ui-kit и mui?

2023-06-20 12:23 UTC, dmitryduy commented on src/shared/package/classname/index.ts
> +};
Если все таки вы решили оставить кастомную реализацию, то посмотри, как это сделано в самой библиотеке classnames

2023-06-20 12:23 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useIntersectionObserver.ts
> +};
Так чего? не будем поддерживать IOS?

2023-06-20 12:23 UTC, dmitryduy commented on src/shared/package/react-hooks/core/useToggle.ts
> +		}
это прям копия хука useThrottle. Может его переиспользовать?

2023-06-20 16:31 UTC, OddEer0 commented on .eslintrc.json
> -		"import/order": [
Нет, они впринципе не работали

2023-06-20 16:32 UTC, OddEer0 commented on src/shared/api/types/User.ts
> +	avatar: string;
Ну, с типами потом в миграций на effector буду разбираться. Тут для того что-бы не ругалось

2023-06-20 16:33 UTC, OddEer0 commented on src/shared/ui/inputs/TextArea/TextArea.tsx
>  export const TextArea: FC<PropsWithChildren<TextAreaProps>> = ({ label = '', className = '', children, ...props }) => {
Да, есть компоненты которых нет на mui, но такие нужны

2023-06-20 16:34 UTC, OddEer0 commented on src/entities/User/model/user.slice.ts
> +				lastName: '',
всё равно при переходе на effector поменяем

2023-06-20 16:35 UTC, OddEer0 commented on src/shared/package/react-hooks/core/useIntersectionObserver.ts
> +};
Этот хук как бы возможно даже не будет использоваться, тут под вопросом

2023-06-20 16:35 UTC, OddEer0 commented on src/shared/package/react-hooks/core/useToggle.ts
> +		}
хорошая идея так-то

2023-06-20 17:33 UTC, merged