[refactor/WF-152]:  set up client authorization
Illusory-Team/work-fly-client pull request #50
Opened 2023-07-28 15:00 UTC by edword03

## Auth - set up client authorization

### Describe task
Add authorization by client side, refactor axios interceptor
Add check auth on register and login pages

### Issue ticket number and link
WF-152
https://illusory-team.atlassian.net/browse/WF-152

### Screens/videos (if there)

### TBD (if there)

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [ ] If it is a core feature, I have added thorough tests.

2023-07-28 15:35 UTC, Stepasha419a requested changes

2023-07-28 15:35 UTC, Stepasha419a commented on src/application/providers/AxiosInterceptor.tsx
> +'use client';
не кажется, что слишком здесь всё спутано? Мне кажется, что проще будет сделать interceptor на уровне инициализации инстанса axios в shared/api, а логику по router.push, то есть валидации вынести в withAuth HOC

2023-07-28 15:35 UTC, Stepasha419a commented on src/entities/User/model/user.api.ts
> +		store.isAuthenticated = true;
только щас заметил. Может логику по auth вынести в отдельную сущность, где будет isAuth и isLoading, чтобы разделить?

2023-07-28 15:35 UTC, Stepasha419a commented on src/features/Auth/lib/hooks/useAuthRedirect.ts
> +'use client';
interceptor, hoc и hook выполняют одну и ту же логику по сути. Может удалить лишнее и реализовать комментарий про разъединение сверху?

2023-07-29 09:45 UTC, Columbiya commented on app/layout.tsx
> -// это пока временно, будем ждать когда пофиксять баг со стороны next или будем делать аутентификацию на  клиенте
как говорил дядюшка боб, временно оставленные комментарии через время становятся постоянными комментариями

2023-07-29 10:22 UTC, Columbiya commented on src/application/providers/index.ts
> +export const AppProvider = combineProviders(ThemeProvider, QueryProvider, AxiosInterceptor);
Думаю, интерцептор лучше вынести из провайдеров как минимум

2023-07-29 10:24 UTC, Columbiya commented on src/features/Auth/lib/hoc/withAuth.tsx
> +export const withAuth = <P extends object>(WrappedComponent: FC<P>) => {
не лучше будет типизировать Record<string, unknown> чтобы в будущем, если кто то вдруг захочет достать значение из пропса, было явно видно, что этого делать не стоит

2023-07-29 10:25 UTC, Columbiya commented on src/features/Auth/lib/hooks/useAuthRedirect.ts
> +'use client';
почему ты уже третий комментарий на use client ругаешься

2023-07-29 10:28 UTC, Columbiya commented on src/shared/api/services/user.service.ts
> +			const response = await this.api.get<User>('/users/me');
api типизирован? URL сам
лучше типизировать, если представляется возможным, вынести в const enum или просто в enum

2023-08-04 20:31 UTC, Stepasha419a approved these changes

2023-08-04 20:40 UTC, merged